name: weekly docker build

on:
  schedule:
    # Monday midnight
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  weekly-container-build:
    uses: ./.github/workflows/reusable-container-workflow.yaml
    with:
      dockerfile: tools/docker/Dockerfile.ubuntu-dev
      tag: alpha
      image: ghcr.io/${{ github.repository }}
      registry: ghcr.io
      registry_username: ${{ github.repository_owner }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
